### ISSUE TITLE
Clean Code Directory

### ISSUE THREAD

**Issue by iamciera** [ndesaraju/motif_extraction#4]
In the `code` directory there are these files: 
1. `2.Motif_Extraction.ipynb`
2. `full_raw_motif_extraction.ipynb`
3. `non_threshold_only_motif_extraction.ipynb`

- [x] Let's have the only the `non-threshold_only_motif_extraction`.

Is there any reason we can't just have one notebook?

**Comment by ndesaraju** [comment]
There is no real reason for the multiple notebooks, it's just that little things changed in the way that we were running the script and I really didn't want to delete previously working code just in case, but I wanted a new notebook so it would be easier to read. I can definitely remove the old notebooks from the git repo though.

**Comment by iamciera** [comment]
Yes, if you really need the old files you can go back in history. That's the joy of version control.  So just get rid of everything you don't need anymore.
